ARG  BASE_IMAGE=ubuntu:20.04 
(определяет используемые переменные во время сборки)

FROM $(BASE_IMAGE) 
(указывает сервер который будет установлен)

ENV ASPNAETCORE_ENVIRONMENT=Development 
(для назначения среды (переменные сред могут переопредилиться  вдальнейшем при запуске докер командд))

RUN apt-get update (обновление индексов)
RUN apt-get install -y apt-utils (установка пакета)
RUN apt-get install -y curl nginx (установака пакета)
RUN cur-sl https://aka.ms/InstallAzureCLIDed | bash (установка пакета)

WORKDIR etc/nginx
(она она используется для установки рабочего каталога внутри нрашего контейнера)

COPY nginx.conf /etc/nginx/nginx.conf  
(копирует новые файлы или каталоги из из тагa /src/ и добавляет их в файловую систему контейнера)

ADD mysite.tag.gz/etc/nginx/sites-available/
(используется аналолгично как COPY он позволяет также задать в /src/ дополнительное значени 
если параметр адресс будет присутсвовать как архив то он его распакует, 
но единственная разница от COPY он не поддерживает команду -2from )

EXPOSE 80 (указывает порт который будет слушать контейнер)

ENTRYPOINT ["nginx"] ()

CMD ["nginx", "-g", "daemon off;"] ()
